### ISSUE TITLE
No installation and operational instruction

### ISSUE THREAD

**Issue by gritsulyak** [Nable80/wwwconf#2]
Ok, it is compiled.

How to run it locally?

**Comment by Nable80** [comment]
Duplicate of https://code.google.com/archive/p/wwwconf/issues/1 >_<

Here's a simple way to get started (don't forget to install uwsgi-core):
<pre># create initial database
./dbtool -n
# (optional step) create user 'Admin' with password 'AdminPass':
./dbtool -aa Admin AdminPass
# run single uwsgi worker (no master process) in CGI mode, bind it to port 7542.
uwsgi-core --plugins http,cgi --http-socket :7542 --cgi . --cgi-allowed-ext .cgi --http-socket-modifier1 9 --check-static static
</pre>
Then you can go to http://127.0.0.1:7542/index.cgi

This is suitable for development, for production you should configure some server such as Nginx, Lighttpd, Boa, etc.

**Comment by gritsulyak** [comment]
done, works on Ubuntu 16.04
